/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ser316.dungeonCrawler;

import ser316.dungeonCrawler.core.GameRunner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    /**
     * Main method.
     * @param args application arguments
     */
    public static void main(String[] args) {

        GameRunner m = new GameRunner();
        try {
            m.initializeGame();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }
}
