/*
a * This Java source file was generated by the Gradle 'init' task.
 */
package ser316.dungeonCrawler;

import ser316.dungeonCrawler.character.PlayerCharacter;
import ser316.dungeonCrawler.core.GameRunner;
import ser316.dungeonCrawler.core.Mediator;
import ser316.dungeonCrawler.factories.*;
import ser316.dungeonCrawler.monsters.Monster;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	
    	GameRunner m = new GameRunner();
    	try {
			m.initializeGame();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }
}
